import { FIELD_TYPES } from "./field-types";

export const AVAILABLE_FIELDS = {
  firstName: {
    label: "First Name",
    type: FIELD_TYPES.text,
    visible: true,
    required: true,
    category: "Personal Information",
  },
  lastName: {
    label: "Last Name",
    type: FIELD_TYPES.text,
    visible: true,
    required: true,
    category: "Personal Information",
  },
  email: {
    label: "Email Address",
    type: FIELD_TYPES.email,
    visible: true,
    required: true,
    category: "Contact Information",
  },
  phone: {
    label: "Phone Number",
    type: FIELD_TYPES.tel,
    visible: true,
    required: true,
    category: "Contact Information",
  },
  address: {
    label: "Address",
    type: FIELD_TYPES.address,
    visible: false,
    required: false,
    category: "Contact Information",
  },
  communicationConsent: {
    label: "Communication Consent",
    type: FIELD_TYPES.checkbox,
    visible: true,
    required: true,
    category: "Legal Information",
  },
  dob: {
    label: "Date of Birth",
    type: FIELD_TYPES.date,
    visible: true,
    required: true,
    category: "Personal Information",
  },
  gender: {
    label: "Gender",
    type: FIELD_TYPES.select,
    visible: true,
    required: true,
    options: ["Male", "Female"],
    category: "Personal Information",
  },
  middleName: {
    label: "Middle Name",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Personal Information",
  },
  emergencyContactName: {
    label: "Emergency Contact Name",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Emergency Information",
  },
  emergencyContactPhone: {
    label: "Emergency Contact Phone",
    type: FIELD_TYPES.tel,
    visible: false,
    required: false,
    category: "Emergency Information",
  },
  education: {
    label: "Education Background",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Background Information",
  },
  occupation: {
    label: "Occupation",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Background Information",
  },
  company: {
    label: "Company/Organization",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Background Information",
  },
  languages: {
    label: "Languages Spoken",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Background Information",
  },
  additionalCourses: {
    label: "Misc. Courses Interest",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Course Information",
  },
  referral: {
    label: "How did you hear about us?",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Course Information",
  },
  accessibilityNeeds: {
    label: "Accessibility Requirements",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Special Requirements",
  },
  skillLevel: {
    label: "Skill Level",
    type: FIELD_TYPES.select,
    visible: false,
    required: false,
    options: ["Beginner", "Intermediate", "Advanced"],
    category: "Background Information",
  },
  specialRequirements: {
    label: "Special Requirements",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Course Information",
  },
  goals: {
    label: "Learning Goals",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Course Information",
  },
  marketingConsent: {
    label: "Marketing Consent",
    type: FIELD_TYPES.checkbox,
    visible: true,
    required: false,
    category: "Contact Information",
  },
  photoRelease: {
    label: "Photo Release",
    type: FIELD_TYPES.checkbox,
    visible: false,
    required: false,
    category: "Legal Information",
  },
  termsAndConditions: {
    label: "Terms and Conditions",
    type: FIELD_TYPES.checkbox,
    visible: true,
    required: true,
    category: "Legal Information",
  },
  guardianFirstName: {
    label: "Parent/Guardian First Name",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Parent/Guardian Information",
  },
  guardianLastName: {
    label: "Parent/Guardian Last Name",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Parent/Guardian Information",
  },
  guardianEmail: {
    label: "Parent/Guardian Email",
    type: FIELD_TYPES.email,
    visible: false,
    required: false,
    category: "Parent/Guardian Information",
  },
  guardianPhone: {
    label: "Parent/Guardian Phone",
    type: FIELD_TYPES.tel,
    visible: false,
    required: false,
    category: "Parent/Guardian Information",
  },
  guardianRelationship: {
    label: "Relationship to Student",
    type: FIELD_TYPES.select,
    visible: false,
    required: false,
    options: ["Parent", "Legal Guardian", "Other"],
    category: "Parent/Guardian Information",
  },
  guardianConsent: {
    label: "Parent/Guardian Consent",
    type: FIELD_TYPES.checkbox,
    visible: false,
    required: false,
    category: "Parent/Guardian Information",
  },
  miscConsent: {
    label: "Misc. Consent",
    type: FIELD_TYPES.checkbox,
    visible: false,
    required: false,
    category: "Miscellaneous",
  },
  miscTextField1: {
    label: "Misc. Text Field 1",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Miscellaneous",
  },
  miscTextField2: {
    label: "Misc. Text Field 2",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    category: "Miscellaneous",
  },
  miscTextArea1: {
    label: "Misc. Text Area 1",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Miscellaneous",
  },
  miscTextArea2: {
    label: "Misc. Text Area 2",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    category: "Miscellaneous",
  },
  miscCheckbox1: {
    label: "Misc. Checkbox 1",
    type: FIELD_TYPES.checkbox,
    visible: false,
    required: false,
    category: "Miscellaneous",
  },
  miscCheckbox2: {
    label: "Misc. Checkbox 2",
    type: FIELD_TYPES.checkbox,
    visible: false,
    required: false,
    category: "Miscellaneous",
  },
  volunteerSignature: {
    label: "Your Signature",
    type: FIELD_TYPES.signature,
    visible: true,
    required: true,
    category: "Days of Service",
  },
  volunteerReleaseForm: {
    label: "Volunteer Release Form",
    type: FIELD_TYPES.infoDialog,
    visible: true,
    required: true,
    content: "Add your volunteer release form here...",
    category: "Days of Service",
  },
  safetyGuidelines: {
    label: "Safety Rules and Guidelines",
    type: FIELD_TYPES.infoDialog,
    visible: true,
    required: true,
    content: "Add your safety rules and guidelines here...",
    category: "Days of Service",
  },
  minorVolunteers: {
    label: "Do you have minors/children volunteering with you today?",
    type: FIELD_TYPES.minorVolunteers,
    visible: true,
    required: true,
    category: "Days of Service",
  },
  volunteerHours: {
    label: "Volunteer Hours",
    type: FIELD_TYPES.volunteerHours,
    visible: true,
    required: true,
    category: "Days of Service",
  },
  safetyVideo: {
    label: "Safety Video",
    type: FIELD_TYPES.externalLink,
    visible: true,
    required: true,
    url: "",
    category: "Days of Service",
  },
  dayOfService: {
    label: "Day of Service",
    type: FIELD_TYPES.dayOfService,
    visible: true,
    required: true,
    options: [],
    category: "Days of Service",
  },
  whoAreYou: {
    label: "Where are you coming from?",
    type: FIELD_TYPES.whoAreYou,
    visible: true,
    required: true,
    category: "Days of Service",
  },
};

export const STRUCTURAL_ELEMENTS = {
  header1: {
    label: "Section Header",
    type: FIELD_TYPES.header,
    visible: true,
    required: false,
    content: "New Section",
    variant: "h5",
    category: "Layout Elements",
  },
  textBlock1: {
    label: "Text Block",
    type: FIELD_TYPES.staticText,
    visible: true,
    required: false,
    content: "Enter your text here...",
    category: "Layout Elements",
  },
  divider1: {
    label: "Divider",
    type: FIELD_TYPES.divider,
    visible: true,
    required: false,
    category: "Layout Elements",
  },
  bannerImage: {
    label: "Banner Image",
    type: FIELD_TYPES.bannerImage,
    visible: true,
    required: false,
    url: "",
    category: "Layout Elements",
  },
};
